<?php

return [
    [
        'name' => 'ini',
        'title' => '客户端配置',
        'type' => 'array',
        'value' => [
            'name' => '智能鲜蜂',
            'logo' => '/uploads/20210328/2b78bc80b6b827f780dafc638986206b.jpeg',
            'copyright' => '2021 南京双贝智能科技有限公司',
            'urlschemes' => 'aibee',
            'package_name' => 'aibee',
            'cdnurl' => 'https://s.aijiehun.com',
            'appurl' => 'https://api.aijiehun.com',
            'socketurl' => 'wss://chat.aijiehun.com',
            'debug' => 'N',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '客户端参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'sdk_amap',
        'title' => '高德地图SDK配置',
        'type' => 'array',
        'value' => [
            'amapkey_web' => '0a9f67a6f8f7cc3315d30846a0fde88b',
            'amapkey_ios' => 'd8b84cf540bcca9928db69b0119fc152',
            'amapkey_android' => '6c3f7522aab215e0704225adaad9f73e',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '高德地图SDK参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'sdk_qq',
        'title' => '腾讯开放SDK配置',
        'type' => 'array',
        'value' => [
            'qq_appid' => 'wxade01cf5c28a04c0',
            'gz_appid' => 'wxade01cf5c28a04c0',
            'wx_appid' => 'wxade01cf5c28a04c0',
            'wx_appsecret' => '525a24ba98262db64130f0d7be412a80',
            'wx_universal_links' => 'https://aijiehun.com/',
            'mch_id' => '1555897421',
            'key' => 'qwertyuiopyang111111111111111111',
            'notify_url' => '/wanlshop/callback/notify/type/wechat',
            'pay_cert' => '0',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '腾讯开放SDK参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'sdk_alipay',
        'title' => '支付宝SDK配置',
        'type' => 'array',
        'value' => [
            'app_id' => '20************21',
            'notify_url' => '/wanlshop/callback/notify/type/alipay',
            'return_url' => '/wanlshop/callback/return/type/alipay',
            'ali_public_key' => '',
            'private_key' => '',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '支付宝SDK参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'sdk_weibo',
        'title' => '微博开放SDK配置',
        'type' => 'array',
        'value' => [
            'appkey' => '35********94',
            'appsecret' => '0a********************************7f',
            'redirect_uri' => '/wanlshop/callback/weibo',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '微博开放SDK参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'kuaidi',
        'title' => '快递100 SDK',
        'type' => 'array',
        'value' => [
            'secretKey' => 'gm********34',
            'callbackUrl' => '/wanlshop/callback/kuaidi',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '快递100 SDK参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'h5',
        'title' => 'H5客户端',
        'type' => 'array',
        'value' => [
            'domain' => 'https://c.aijiehun.com',
            'title' => '智能鲜蜂',
            'router_mode' => 'hash',
            'router_base' => '/',
            'https' => 'Y',
            'qqmap_key' => 'V3JBZ-C7Z36-BL7S6-M67TX-6WORS-2TBMN',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => 'H5客户端配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'mp_weixin',
        'title' => '微信小程序',
        'type' => 'array',
        'value' => [
            'appid' => 'wxade01cf5c28a04c0',
            'appsecret' => '525a24ba98262db64130f0d7be412a80',
            'scope_userLocation' => '演示定位能力',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '微信小程序配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'mp_alipay',
        'title' => '支付宝小程序',
        'type' => 'array',
        'value' => [
            'appid' => '20**********76',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '支付宝小程序配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'mp_baidu',
        'title' => '百度小程序',
        'type' => 'array',
        'value' => [
            'appid' => '',
            'appsecret' => '',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '百度小程序配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'mp_toutiao',
        'title' => '头条小程序',
        'type' => 'array',
        'value' => [
            'appid' => '',
            'appsecret' => '',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '头条小程序配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'mp_qq',
        'title' => 'QQ小程序',
        'type' => 'array',
        'value' => [
            'appid' => '11*****49',
            'appsecret' => 'EV***************HX',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => 'QQ小程序配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'style',
        'title' => '样式配置',
        'type' => 'array',
        'value' => [
            'category_style' => '4',
            'find_bg_color' => '#f7f7f7',
            'find_bg_image' => '/assets/addons/wanlshop/img/find/top_bg.png',
            'find_font_color' => 'light',
            'cart_nav_image' => '',
            'cart_nav_color' => '',
            'cart_font_color' => '',
            'user_nav_color' => '#ffeccc',
            'user_nav_image' => '/assets/addons/wanlshop/img/user/top_bg.png',
            'user_bg_color' => '#ffeccc',
            'user_bg_image' => '/assets/addons/wanlshop/img/user/user_bg.png',
            'user_font_color' => '',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => 'App样式配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'config',
        'title' => '动态客户端配置',
        'type' => 'array',
        'value' => [
            'store_audit' => 'Y',
            'comment_switch' => 'Y',
            'tel_phone' => '13236390680',
            'working_hours' => '09:00~22:00',
            'shop_document' => '',
            'shop_qun' => '',
            'user_agreement' => '153',
            'privacy_protection' => '154',
            'help_category' => '1',
            'new_category' => '2',
            'sys_category' => '4',
            'auth_reply' => '欢迎使用智能鲜蜂客服',
            'not_online' => '[汗] 非工作时间8:00-22:00 或客服繁忙！请稍后再试~',
            'service_initial' => '您好 [微笑] 请用一句话简短描述问题~',
            'mp_weixin_id' => 'wxade01cf5c28a04c0',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => 'App参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'order',
        'title' => '订单配置',
        'type' => 'array',
        'value' => [
            'cancel' => '3',
            'receiving' => '7',
            'comment' => '7',
            'customer' => '7',
            'autoagree' => '3',
            'returntime' => '7',
            'receivingtime' => '7',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '订单参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'find',
        'title' => '直播配置',
        'type' => 'array',
        'value' => [
            'app_switch' => [
                'all' => 'all',
                'new' => 'new',
                'live' => 'live',
                'want' => 'want',
                'show' => 'show',
            ],
            'mp_switch' => [
                'all' => 'all',
                'new' => 'new',
                'live' => 'live',
                'want' => 'want',
                'show' => 'show',
            ],
            'h5_switch' => [
                'all' => 'all',
                'new' => 'new',
                'live' => 'live',
                'want' => 'want',
                'show' => 'show',
            ],
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '订单参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'live',
        'title' => '直播配置',
        'type' => 'array',
        'value' => [
            'liveDomain' => 'live.aijiehun.com',
            'pushDomain' => 'rtmp.aijiehun.com',
            'builderTime' => '60',
            'pushKey' => '0*****v',
            'liveKey' => 'l*****d',
            'liveCnd' => 'https://play.aijiehun.com',
            'appName' => 'aibee',
            'transTemplate' => 'ld',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '订单参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'withdraw',
        'title' => '提现配置',
        'type' => 'array',
        'value' => [
            'state' => 'Y',
            'minmoney' => '1',
            'monthlimit' => '10',
            'servicefee' => '6',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '商城提现参数配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => '__tips__',
        'title' => '温馨提示',
        'type' => 'string',
        'content' => [],
        'value' => '不需要此处配置任何参数，请在 [多用户商城] - [客户端管理]和[系统管理] 中管理配置',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];
